#cloud-config
rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
        address: 192.168.1.21/24
        gateway: 192.168.1.1
        mtu: 1500
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4